### ISSUE TITLE
Snowpipe feature

### ISSUE THREAD

**Issue by mced** [transferwise/pipelinewise-target-snowflake#103]
I see that target uses a conventional database connection to copy csv files into snowflake table.
Do you think this "target" covers snowpipe usage or do you think that fits to another target ?

https://docs.snowflake.com/en/user-guide/data-load-snowpipe-intro.html
https://github.com/snowflakedb/snowflake-ingest-python

**Comment by koszti** [comment]
Using [pipelinewise-tap-s3-csv](https://github.com/transferwise/pipelinewise-tap-s3-csv) together with this target basically covers snowpipe usage.

**Comment by mced** [comment]
Thanks @koszti !
