### ISSUE TITLE
Help with 'This session does not have a current schema.  Call 'USE SCHEMA' error

### ISSUE THREAD

**Issue by OB2B** [transferwise/pipelinewise-target-snowflake#120]
Hello!  First off - I'm new to transferwise and pipelinewise and here because of high Fivetran costs.  Love what I have seen of this product.

I have a PostGres tap and Snowflake target.  The pipeline is erroring at the point where it is copying data from the Snowflake staged file, into the schema table.  I've spent a good 10 hours trying to get past this point and would really appreciate help!

The error in Snowflake is: 
` 'Cannot perform operation. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name'.

COPY INTO bss_stg."SERVER_TEMP" FROM '@pipelinewise_encrypted_etl_stage/snowflake-imports-from-RDS/pipelinewise_public.netsuite_server_20201211-144949.csv.gz' FILE_FORMAT = (type=CSV escape='\x1e' escape_unenclosed_field='\x1e' field_optionally_enclosed_by='"' skip_header=0 compression=GZIP binary_format=HEX)`

Here is the pipelinewise error:
[

Full log: /root/.pipelinewise/snowflake/postgres_sample/log/snowflake-postgres_sample-20201211_152455.fastsync.log.failed
Traceback (most recent call last):
  File "/app/pipelinewise/cli/pipelinewise.py", line 1014, in run_tap
    transform=transform_params)
  File "/app/pipelinewise/cli/pipelinewise.py", line 909, in run_tap_fastsync
    commands.run_command(command, self.tap_run_log_file)
  File "/app/pipelinewise/cli/commands.py", line 361, in run_command
    raise RunCommandException(f'Command failed. Return code: {proc_rc}\n'
pipelinewise.cli.commands.RunCommandException: Command failed. Return code: 1
Error(s) found:
time=2020-12-11 15:24:59 logger_name=pipelinewise.fastsync.postgres_to_snowflake log_level=ERROR message=090106 (22000): Cannot perform operation. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.
    cursor.errorhandler(connection, cursor, error_class, error_value)
snowflake.connector.errors.ProgrammingError: 090106 (22000): Cannot perform operation. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.
time=2020-12-11 15:24:59 logger_name=pipelinewise.fastsync.postgres_to_snowflake log_level=ERROR message=090106 (22000): Cannot perform operation. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.
    cursor.errorhandler(connection, cursor, error_class, error_value)
snowflake.connector.errors.ProgrammingError: 090106 (22000): Cannot perform operation. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.

Full log: /root/.pipelinewise/snowflake/postgres_sample/log/snowflake-postgres_sample-20201211_152455.fastsync.log.failed
time=2020-12-11 15:24:59 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=
-------------------------------------------------------
TAP RUN SUMMARY
-------------------------------------------------------
    Status  : FAILED
    Runtime : 0:00:04.447086
-------------------------------------------------------]

The user has a default_namespace set in Snowflake; i.e., default Schema.

Here is the current target_snowflake.yml file.  I've tried different variations to get the target schema in, hence the extra default_target_schema here

db_conn:
  account: "xxx"                  # Snowflake account
  dbname: "FIVETRAN"                            # Snowflake database name
  default_target_schema: "BSS_STG"
  user: "PIPELINEWISE"                                # Snowflake user
  password: "xxx"                        # Plain string or vault encrypted
  warehouse: "FIVETRAN_WAREHOUSE"               # Snowflake virtual warehouse

**Comment by Samira-El** [comment]
Hey Karen!

I'm glad to read that you love PipelineWise!

> COPY INTO bss_stg."SERVER_TEMP" FROM '@pipelinewise_encrypted_etl_stage/snowflake-imports-from-RDS/pipelinewise_public.netsuite_server_20201211-144949.csv.gz' FILE_FORMAT = (type=CSV escape='\x1e' escape_unenclosed_field='\x1e' field_optionally_enclosed_by='"' skip_header=0 compression=GZIP binary_format=HEX)`


It seems like the issue is in the stage name, Snowflake doesn't know where this stage is.
Do you by any have the `stage` property in `target_snowflake.yml` equals to `pipelinewise_encrypted_etl_stage`? if so, please update it to include the schema name where the stage is.

**Comment by OB2B** [comment]
Hi Samira-El!

That was it, thank you.  My target_snowflake stage and file_formats were missing the schema names.  All set now!

Best Regards,
Karen
