### ISSUE TITLE
Can't define primary_key_required

### ISSUE THREAD

**Issue by ashalitkin** [transferwise/pipelinewise-target-snowflake#200]
I'm using pipelinewise to transfer data from postgres to snowflake and for the full table sync I need to specify primary_key_required: False. I'm trying to add this key to the corresponding pipelinewise yml file but it doesn't work. This flag is always set to True.

**Comment by Samira-El** [comment]
Hey, try setting it in the tap file, at the root level.

**Comment by ashalitkin** [comment]
yes, it works. Thanks a lot, @Samira-El !
