### ISSUE TITLE
Emit State More Often

### ISSUE THREAD

**Issue by andyoneal** [transferwise/pipelinewise-target-snowflake#21]
From the [guidelines](https://github.com/singer-io/getting-started/blob/master/docs/RUNNING_AND_DEVELOPING.md): 
> Write State messages to stdout once all data that appeared in the stream before the State message has been processed by the Target. 

It would be helpful if state was emitted more often than just at the very end of the run. I'm currently trying to set up a sync from a large number of tables in a database and as some errors occur which halt the process mid-run. Even though a huge chunk of the data has already been processed, I'm having to start from scratch and copy redundant data until it catches up.

Could state be emitted as they are received and handled?

**Comment by koszti** [comment]
writing state more often is a top item in our backlog and will arrive soon.

**Comment by koszti** [comment]
addressed in v1.0.9 and it's fixed and improved in the latest v1.1.6 ([PyPI v1.1.6](https://pypi.org/project/pipelinewise-target-snowflake/1.1.6/))
