### ISSUE TITLE
Make parallel file uploads available for table stages again

### ISSUE THREAD

**Issue by fred-oloughlin** [transferwise/pipelinewise-target-snowflake#223]
**Is your feature request related to a problem? Please describe.**
The PUT command for the python connector became thread-safe in v2.4.2. This project is [currently using 2.4.6](https://github.com/transferwise/pipelinewise-target-snowflake/blob/master/setup.py#L22).

**Describe the solution you'd like**
It is now possible to revert [this commit](https://github.com/transferwise/pipelinewise-target-snowflake/commit/62b7d1c4dac22e4eca183db89f2f571a06b0c92a#), in order to allow parallel file uploads on table stages.

**Describe alternatives you've considered**
N/A

**Additional context**
See release note for python connector v2.4.2(April 03,2021): https://pypi.org/project/snowflake-connector-python/

**Comment by Samira-El** [comment]
Hey @fred-oloughlin , thanks for raising this, it makes sense to me to revert that commit. Would you be open to sending a PR for that :) ?

**Comment by fred-oloughlin** [comment]
Thanks @Samira-El, yep very happy to! Here you go: https://github.com/transferwise/pipelinewise-target-snowflake/pull/227
