### ISSUE TITLE
Load failure with CSV and also with a Large Batchsize

### ISSUE THREAD

**Issue by s7clarke10** [transferwise/pipelinewise-target-snowflake#225]
Hi,

I have experienced two issues running target-snowflake with data from Salesforce recently. 

I have been using the default batch_size settings for the pipelinewise target-snowflake i.e. the batch_size_rows = 100,000 records when loading the data via a Parquet format via an external S3 bucket. I’m using Parquet because the job failed with an invalid character when I used a CSV format and crashed (see Issue 2).

The issue is the job refuses to process if I use the default setting of 100,000 records. I decide to back it off and changed it to 50,000 records and it loads.  I would have thought however given the default was 100,000 rows that it should be okay. Is there some sort of limit for Parquet or other components possibly?

**Issue 1: Jobs fail when loading 100,000 rows with a Parquet file**.

So to have some successful loads, I have had use a Parquet format and to back off the batch_size_rows to 50,000 rows. It appears that I can successfully load after that. I am running my job via Meltano in a Docker container in AWS ECS with a Task memory (MiB) 4096, and Task CPU (unit) 1024. Perhaps given the volume of data it sized a little too small for this initial load of at 500,000 row table? I would be interested in your thoughts on this and the CSV error that I received. It is also possible that there may be some limit with S3 Copy and Parquet possibly?

Unfortunately there is no meaningful error message provided, just that the pipeline failed. Given number of rows being processed, I feel it would be difficult to get a log given all the data being processed.

**Side Note:** Is it possible to just add records with target-snowflake like a log with an operation type indicate whether it was an Insert, Update, or Delete. I understand it does a merge by default. I was curious whether I could control this behaviour?

**Issue 2: CSV Format is failing to load** 

I couldn't load my Salesforce table using a CSV Format. I was successful with other tables however. I'm guessing it is a combination of data which is upsetting the CSV Format?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/sclarke/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/sclarke/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<label class=awsui-checkbox for=awsui-checkbox-4007
 id=awsui-checkbox-4007-label style='display:flex'>
 <div style='flex-shrink: 0;user-select: none;height:1.4rem;width:1.4rem'></div>
</label>
<label class=awsui-checkbox for=awsui-checkbox-4008
 id=awsui-checkbox-4008-label style='display:flex'>
 <div style='flex-shrink: 0;user-select: none;height:1.4rem;width:1.4rem'></div>
</label>
<label class=awsui-checkbox for=awsui-checkbox-4009
 id=awsui-checkbox-4009-label style='display:flex'>
 <div style='flex-shrink: 0;user-select: none;height:1.4rem;width:1.4rem'></div>
</label>
<label class=awsui-checkbox for=awsui-checkbox-4010
 id=awsui-checkbox-4010-label style='display:flex'>
 <div style='flex-shrink: 0;user-select: none;height:1.4rem;width:1.4rem'></div>
</label>
<label class=awsui-checkbox for=awsui-checkbox-4011
 id=awsui-checkbox-4011-label style='display:flex'>
 <div style='flex-shrink: 0;user-select: none;height:1.4rem;width:1.4rem'></div>
</label>

<body link="#0563C1" vlink="#954F72">

target-snowflake   \| loader \| Traceback (most recent call last):
--
target-snowflake   \| loader \| File   "/project/.meltano/loaders/target-snowflake/venv/bin/target-snowflake",   line 8, in <module>
target-snowflake   \| loader \| sys.exit(main())
target-snowflake   \| loader \| File   "/project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/target_snowflake/__init__.py",   line 520, in main
target-snowflake   \| loader \| persist_lines(config, singer_messages, table_cache,   file_format_type)
target-snowflake   \| loader \| File   "/project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/target_snowflake/__init__.py",   line 210, in persist_lines
target-snowflake   \| loader \| flushed_state = flush_streams(
target-snowflake   \| loader \| File   "/project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/target_snowflake/__init__.py",   line 377, in flush_streams
target-snowflake   \| loader \| Parallel()(delayed(load_stream_batch)(
target-snowflake   \| loader \| File   "/project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/joblib/parallel.py",   line 1043, in __call__
target-snowflake   \| loader \| if self.dispatch_one_batch(iterator):
target-snowflake   \| loader \| File   "/project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/joblib/parallel.py",   line 861, in dispatch_one_batch
target-snowflake   \| loader \| self._dispatch(tasks)
target-snowflake   \| loader \| File   "/project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/joblib/parallel.py",   line 779, in _dispatch
target-snowflake   \| loader \| job = self._backend.apply_async(batch, callback=cb)
target-snowflake   \| loader \| File   "/project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/joblib/_parallel_backends.py",   line 208, in apply_async
target-snowflake   \| loader \| result = ImmediateResult(func)
target-snowflake   \| loader \| File   "/project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/joblib/_parallel_backends.py",   line 572, in __init__
target-snowflake   \| loader \| self.results = batch()
target-snowflake   \| loader \| File   "/project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/joblib/parallel.py",   line 262, in __call__
target-snowflake   \| loader \| return [func(*args, **kwargs)
target-snowflake   \| loader \| File   "/project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/joblib/parallel.py",   line 262, in <listcomp>
target-snowflake   \| loader \| return [func(*args, **kwargs)
target-snowflake   \| loader \| File   "/project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/target_snowflake/__init__.py",   line 419, in load_stream_batch
target-snowflake   \| loader \| flush_records(stream, records, db_sync, temp_dir, no_compression,   archive_load_files)
target-snowflake   \| loader \| File   "/project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/target_snowflake/__init__.py",   line 465, in flush_records
target-snowflake   \| loader \| db_sync.load_file(s3_key, row_count, size_bytes)
target-snowflake   \| loader \| File   "/project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/target_snowflake/db_sync.py",   line 478, in load_file
target-snowflake   \| loader \| cur.execute(merge_sql)
target-snowflake   \| loader \| File   "/project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/snowflake/connector/cursor.py",   line 721, in execute
target-snowflake   \| loader \| Error.errorhandler_wrapper(
target-snowflake   \| loader \| File   "/project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/snowflake/connector/errors.py",   line 258, in errorhandler_wrapper
target-snowflake   \| loader \| cursor.errorhandler(connection, cursor, error_class, error_value)
target-snowflake   \| loader \| File   "/project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/snowflake/connector/errors.py",   line 188, in default_errorhandler
target-snowflake   \| loader \| raise error_class(
target-snowflake   \| loader \| **snowflake.connector.errors.ProgrammingError: 100065 (22000): Found   character '/' instead of field delimiter ','**
target-snowflake   \| loader \| File   'pipelinewise_my_table__c_20211029-045830-264783_batch__tflfc8h.csv.gz',   line 1, character 124
target-snowflake   \| loader \| Row 1, column   "TRANSIENT_STAGE_TABLE"["$24":24]

</body>

</html>

I really like your work on this Singer Target - I recently contributed the an enhancement to accept a datetype of date.

Your thoughts on these issues would be much appreciated.
Thanks
Steve

**Comment by s7clarke10** [comment]
Update: I have continued to experiment with adjusting resources allocated to my Docker / Fargate environment.

1. Increase the Ephemeral storage from 20GiB -> 200GiB. Result : Still failing
2. Double the Memory and CPU resources from:
    1024 CPU (1 vCPU) -> 2048 (2 vCPU)
    4096 Memory (4 GB) -> 8192 (8 GB)
   
With the increase in the CPU and Memory I was able to successfully ingest a large table with the batch size set to 100,000 records. I'm guessing that some sort of limit was being hit. Will need to experiment further to determine whether it is CPU or Memory related, I'm guessing it is memory related.

**Comment by Samira-El** [comment]
hey @s7clarke10, I reckon you're hitting memory limit here, because the target keeps the data in memory until it reaches the configured batch size then flushes it csv/parquet file.

**Comment by s7clarke10** [comment]
Hi @Samira-El , thank you very much for this feedback. For some reason I had a working assumption that data was being written to disk rather than memory - that is great to know, I appreciate your help.

In a related question, I have a very large table coming from Salesforce 'Case' with millions of rows and over 500 columns. Despite me changing the batch_size_rows  10,000 and batch_wait_limit_seconds to 1800. It seems to keep running the tap until it eventually runs out of memory. I would have expected reading the code for batch_wait_limit_seconds that after 30 minutes the target-snowflake would force a write of batches?

Have I misunderstood the purpose of this parameter? Are you aware of any factors that would prevent records being written out after that time duration is hit?

Thanks Steve.

**Comment by s7clarke10** [comment]
Hi @Samira-El,

That was the key problem I wasn't seeing any "Flush triggered by ..." messages in the log. It would keep creating batches and then fail after 2-3 hours without sending anything to Snowflake.

Given the comments about memory I have re-created my environment and allocated 16GB. I did drop the batch_size_rows to 10,000 records and I can now see this coming into my log tonight. Once the table is ingested, I will do a re-run with the batch_size_rows = 100,000 and see if the time kicks in.

I'm getting the feeling there was some strange intermittent issue at play. I will report back my findings. Thanks.

**Comment by s7clarke10** [comment]
Hi, I have re-run again with no problems when I doubled my memory from 8GB -> 16GB. I enabled CloudWatch Metrics and it was showing that I was reaching 59% of memory being used. I therefore conclude that memory was the issue and it was interfering with the triggering functionality.

I'm happy to close this Issue. Thank you very much for your input.

**Comment by Samira-El** [comment]
Glad you figure it out :)
