### ISSUE TITLE
Target does not emit latest state if no records are written

### ISSUE THREAD

**Issue by zyzil** [transferwise/pipelinewise-target-snowflake#238]
**Describe the bug**
I am using the Snowflake target with a custom singer tap that emits state to track a watermark (MongoDB change streams resume token). This singer taps starts with the last resume token, asks MongoDB for any related documents since the last resume token, and then updates the token to the latest value from MongoDB. MongoDB's change resume token is updated even if there are no documents found. This is to facilitate keeping up with the oplog/change stream to ensure you don't use a resume token that falls out of the oplog.

Due to how the Snowflake target implements state with the flushed_state, the flushed state is never updated if there were no records emitted from the tap. This causes the target to emit the initial state written by the tap instead of the latest current state from the tap.

**To Reproduce**
1. Utilize the Snowflake target with a target that emits multiple state messages even if no records are emitted. I am using an internal tap that cannot be shared unfortunately.
2. If you run the tap by itself to stdout you will see the latest correct state message emitted
3. If you run the tap piped to the Snowflake target, you will see that it emits the first state record instead of the latest

**Expected behavior**
Singer targets should always emit the latest state message. The latest state emitted by the tap should be passed through and emitted by the Snowflake target.

**Your environment**
 - Version of target: 1.14.1
 - Version of python: 3.8

**Comment by Samira-El** [comment]
Hi @zyzil , thanks for raising this!

I was able to reproduce this by feeding these streams into the target:
```ndjson
{"type": "SCHEMA", "stream": "tap_mysql_test-test_simple_table", "schema": {"properties": {"id": {"maximum": 9223372036854775807, "minimum": -9223372036854775808, "type": ["integer"]}, "results": {"type": ["null", "string"]}, "time_created": {"type": ["null", "string"]}}, "type": "date-time"}, "key_properties": ["id"], "bookmark_properties": ["id"]}
{"type": "STATE", "value": {"bookmarks": {"tap_mysql_test-test_simple_table": {"replication_key": "id", "replication_key_value": 1, "version": 1}}}}
{"type": "ACTIVATE_VERSION", "stream": "tap_mysql_test-test_simple_table", "version": 1}
{"type": "STATE", "value": {"bookmarks": {"tap_mysql_test-test_simple_table": {"replication_key": "id", "replication_key_value": 2, "version": 1}}}}
{"type": "STATE", "value": {"bookmarks": {"tap_mysql_test-test_simple_table": {"replication_key": "id", "replication_key_value": 3, "version": 1}}}}
{"type": "STATE", "value": {"bookmarks": {"tap_mysql_test-test_simple_table": {"replication_key": "id", "replication_key_value": 5, "version": 1}}}}
{"type": "STATE", "value": {"bookmarks": {"tap_mysql_test-test_simple_table": {"replication_key": "id", "replication_key_value": 6, "version": 1}}}}
{"type": "STATE", "value": {"bookmarks": {"tap_mysql_test-test_simple_table": {"replication_key": "id", "replication_key_value": 7, "version": 1}}}}
{"type": "STATE", "value": {"bookmarks": {"tap_mysql_test-test_simple_table": {"replication_key": "id", "replication_key_value": 10, "version": 1}}}}
{"type": "STATE", "value": {"bookmarks": {"tap_mysql_test-test_simple_table": {"replication_key": "id", "replication_key_value": 45, "version": 1}}}}
{"type": "STATE", "value": {"bookmarks": {"tap_mysql_test-test_simple_table": {"replication_key": "id", "replication_key_value": 100, "version": 1}}}}
```

The target at the end emitted one state which is the first one
```
time=2021-12-15 15:41:50 name=target_snowflake level=INFO message=Emitting state {"bookmarks": {"tap_mysql_test-test_simple_table": {"replication_key": "id", "replication_key_value": 1, "version": 1}}}
{"bookmarks": {"tap_mysql_test-test_simple_table": {"replication_key": "id", "replication_key_value": 1, "version": 1}}}
```

Can you confirm this it the bug that you're facing?

**Comment by zyzil** [comment]
@Samira-El, Yes this is indeed the behavior I am seeing which is causing me problems. I'm glad you were able to quickly reproduce it!

**Comment by Samira-El** [comment]
Great, thanks! Will work on a fix in the upcoming days.

**Comment by Samira-El** [comment]
Fix is available so closing this issue!
