### ISSUE TITLE
Use a different name for 'COLUMNS' control table or make it configurable

### ISSUE THREAD

**Issue by johnoscott** [transferwise/pipelinewise-target-snowflake#27]
Destination control table 'COLUMNS' seems too generic and might clash with the User's source schema. Suggest changing it to a name that not only reduces name clash, but identifies it as belonging to PipelineWise e.g.  `_$PIPELINEWISE_COLUMNS` or make it configurable.

**Comment by Samira-El** [comment]
Hey @johnoscott, having this would be awesome. Would be great if you could contribute and do the coding part, we'd be happy to help where we can.

**Comment by koszti** [comment]
closing this because no more `PIPELINEWISE.COLUMNS` table since 1.6.1. More info about the changes at https://github.com/transferwise/pipelinewise-target-snowflake/pull/67
