### ISSUE TITLE
ujson.JSONDecodeError: Value is too big!

### ISSUE THREAD

**Issue by joeythedataguy** [transferwise/pipelinewise-target-snowflake#273]
Hello,

i'm getting an error coming from this [line](https://github.com/transferwise/pipelinewise-target-snowflake/blob/b5536e2a2dbc42fa7e325d99b5cea4c0f484b392/target_snowflake/__init__.py#L123).

In json generated as part of `meltano elt` I got singer schema json with values likes this:
```
"weight": {
    "type": [
        "null",
        "number"
    ],
    "exclusiveMaximum": true,
    "maximum": 100000000000000000000000000000000000000000000000000000000000000,
    "multipleOf": 1e-38,
    "exclusiveMinimum": true,
    "minimum": -100000000000000000000000000000000000000000000000000000000000000
},
```

And ujson library cannot parse out value like this.

**Comment by Tolsto** [comment]
I have the same problem. I don't think that ujson is a good choice for data integration tools, see https://github.com/ultrajson/ultrajson/issues/99 @koszti

**Comment by koszti** [comment]
thanks for reporting it, we're going to revert and will go back from ujson to the standard python json library.

**Comment by koszti** [comment]
https://github.com/transferwise/pipelinewise-target-snowflake/pull/278 - linking to PR

**Comment by Samira-El** [comment]
Closing this as change has been reverted.
