### ISSUE TITLE
Array type records fail to load in Snowflake

### ISSUE THREAD

**Issue by n-batalha** [transferwise/pipelinewise-target-snowflake#28]
First report without a minimal reproducible environment in case it's understood easily / known. I can make such an environment if required.

---

Using version 1.0.8 as a singer target alongside a custom singer tap (`tap-customsource | target-snowflake`), I find that I have issues when loading records in Snowflake. 

A dataset which is just strings and integers is fine. The issue is when using arrays and possibly objects.

An `array` field in the tap is mapped to a `VARIANT` column in Snowflake created by this target. The actual csv produced by this target in s3 has "[1,2]" which leads to what seems like Snowflake interpreting two columns due to the `','` delimiter (leading to data validation issues as it expects data of different types in the respective positions). If I escape the comma (`"[1\, 2]"`) it seems to load fine. 

I see mentions online of Snowflake not supporting arrays/objects loaded via csv yet this target suggests it supports this data without flattening. 

Thanks!

**Comment by koszti** [comment]
This is interesting, we load lot of JSON objects directly to VARIANT columns with this connector. I remember we had some issues with loading arrays (not objects) into VARIANT but AFAIK that has been fixed some time ago.

There is a test case that loads array and object into VARIANT columns and it's passing:
https://github.com/transferwise/pipelinewise-target-snowflake/blob/master/tests/integration/test_target_snowflake.py#L345

Can you see any differences that might give some clue?

**Comment by n-batalha** [comment]
Thanks, I've dumped the output of my tap and the only visible difference I'm spotting is that the array in your test is defined as an object `"c_array": {"type": ["null", "object"]}`

**Comment by n-batalha** [comment]
I've built a small test case that confirms the remark above.

```
cat <file> | target-snowflake -c config.json
```
Where `<file>` is one of the attached. One has an array and the loading to snowflake fails. I replace the array with an object and the load succeeds.

[sample_formatted-array-oneline.txt](https://github.com/transferwise/pipelinewise-target-snowflake/files/3706846/sample_formatted-array-oneline.txt)
[sample_formatted-object-oneline.txt](https://github.com/transferwise/pipelinewise-target-snowflake/files/3706847/sample_formatted-object-oneline.txt)

**Comment by koszti** [comment]
@n-batalha can you please try attaching the files again? It cannot be downloaded for some reason.

**Comment by koszti** [comment]
@n-batalha thanks for the examples. I tried to load your samples into snowflake and seems like objects and arrays loaded correctly into VARANT columns. Can you see any differences in your environment? I attached the commands, results, an example `config.json` that I used and when trying to reproduce the problem. Please share any 

**Pre-check: FILE FORMAT**
Have you created the FILE FORMAT object with these options? The name can be different than `pipelinewise.etl_stage_file_format` but should use these settings. Later the FILE FORMAT name needs to be in your `config.json`:  
```
CREATE file format IF NOT EXISTS pipelinewise.etl_stage_file_format_test
type = 'CSV' escape='\\' field_optionally_enclosed_by='"';
```

**1. sample_formatted-array-online.txt**
`cat sample_formatted-array-oneline.txt  | target-snowflake --config config.json`

<img width="597" alt="Screenshot 2019-10-15 at 10 13 09" src="https://user-images.githubusercontent.com/643687/66818144-c725ec80-ef34-11e9-8b20-397b78b45627.png">

**2. sample_formatted-object-oneline.txt**
`cat sample_formatted-object-oneline.txt | target-snowflake --config config.json`

<img width="593" alt="Screenshot 2019-10-15 at 10 14 09" src="https://user-images.githubusercontent.com/643687/66818152-cb520a00-ef34-11e9-8b41-caab8bb6b987.png">

**3. sample_formatted-object-4-oneline.txt**
` cat sample_formatted-object-4-oneline.txt | target-snowflake --config config.json`

<img width="593" alt="Screenshot 2019-10-15 at 10 14 35" src="https://user-images.githubusercontent.com/643687/66818174-d311ae80-ef34-11e9-97f4-a4111fd65b7a.png">

**config.json**
```
{
    "account": "rtXXXXX.eu-central-1",
    "dbname": "<dbname>",
    "user": "<user>>",
    "password": "<password>",
    "warehouse": "<warehouse>",
    "aws_access_key_id": "<access_key_id>",
    "aws_secret_access_key": "<secret_access_key>",
    "s3_bucket": "tw-staging-analyticsdb-etl",
    "s3_key_prefix": "snowflake-imports-test/",
    "stage": "pipelinewise.encrypted_etl_stage_test",
    "file_format": "pipelinewise.etl_stage_file_format",
    "default_target_schema": "test_array_load"
}
```

**Comment by n-batalha** [comment]
Apologies as missed this, will just need some time as I no longer have a snowflake privileged account (was using the trial for a sandboxed env)

**Comment by n-batalha** [comment]
Good news, I tried this on a checkout of the `v1.1.6` tag and it worked this time. I didn't change anything else, other than the version (to the best of my knowledge, the file format etc were the same). Thanks for looking into this! Hope I didn't had anything wrong before.
