### ISSUE TITLE
Bump max_records on target_snowflake to handle databases larger than 9999 columns

### ISSUE THREAD

**Issue by scottgoering** [transferwise/pipelinewise-target-snowflake#289]
This issue is almost a duplicate of #210 that was fixed with #212 .

The problem I'm running into is that there are two places in the db_sync.py file where max_records is used.  #212 fixed the the first instance: https://github.com/transferwise/pipelinewise-target-snowflake/blob/f18c9e86ca21fdc2cbd8257bf375f664d0f46c3b/target_snowflake/db_sync.py#L644

But there's another instance here: 
https://github.com/transferwise/pipelinewise-target-snowflake/blob/f18c9e86ca21fdc2cbd8257bf375f664d0f46c3b/target_snowflake/db_sync.py#L691

Can we bump the max_records on the second instance to 99999 also?

**Comment by Samira-El** [comment]
Hi, feel free to raise a PR to change this
