### ISSUE TITLE
Does this target support the ACTIVATE_VERSION message?

### ISSUE THREAD

**Issue by robotfelix** [transferwise/pipelinewise-target-snowflake#327]
Sorry if this is a silly question, but does this target support the `ACTIVATE_VERSION` message?

I can see that `ACTIVATE_VERSION` messages are identified here:
https://github.com/transferwise/pipelinewise-target-snowflake/blob/1da448820efeefecdd8f54c67c0d4077f919570c/target_snowflake/__init__.py#L313-L314
and they also feature in a number of test files, but it doesn't look like anything is actually done with the message other than logging it.

My understanding from [here](https://hub.meltano.com/singer/docs/#activate-version) is that, upon receiving this message at the end of a `FULL_TABLE` sync, any existing records in the target table that weren't included in the current run should be deleted (either soft deleted via the `_SDC_DELETED_AT` metadata column or hard deleted).

This doesn't seem to be happening in my testing, so I just thought I'd ask the question directly!

**Comment by Samira-El** [comment]
Hi Felix,
No it doesn't, `ACTIVATE_VERSION` type messages are ignored, the [Singer spec](https://github.com/singer-io/getting-started) doesn't have instructions on what this message means nor what it's supposed to do, they even removed it from the doc.

**Comment by robotfelix** [comment]
Hi Samira-El,
That's a shame to hear, as it would have been perfect for my use case (small table with relatively frequent hard deletes, with our process generally revolving around incremental replication), but thanks for the confirmation either way!
