### ISSUE TITLE
Timestamp format Issue - CSV to Snowflake 

### ISSUE THREAD

**Issue by SaurabhJain2611** [transferwise/pipelinewise-target-snowflake#39]
Is there any way to change the timestamp format while uploading the data from mysql to csv as it is giving error when flushing the csv data from csv (with default timestamp format: 2017-03-26T00:57:23+00:00) to snowflake. I have tried multiple combination of file formats in snowflake but couldn't resolved. 
Sample:
Data in mysql
'1000', 'Voyatouch', '0', '2017-03-26 00:57:23', '2017-03-26 00:57:23', '112'
'999', 'Biodex', '1', '2017-03-26 00:57:23', '2017-03-26 00:57:23', '857'
'998', 'Fix San', '1', '2017-03-26 00:57:23', '2017-03-26 00:57:23', '576'
'997', 'Konklab', '1', '2017-03-26 00:57:23', '2017-03-26 00:57:23', '932'

sample data of the csv created for the above data is given below:
2019-10-18T18:54:31.682242 |   | 2019-10-18T13:24:00.227242Z | 1000 | Voyatouch | 2017-03-26T00:57:23+00:00 | 2017-03-26T00:57:23+00:00 | false | 112

timestamp format in csv has been changed and when it is copying the data into snowflake table it is blowing up with the below error
snowflake.connector.errors.ProgrammingError: 100096 (22007): 018fa104-007d-cfbf-0000-30d900014fba: Can't parse '"2019-10-18T18:54:31.682242"' as timestamp with format 'YYYY-MM-DD"T"HH24:MI:SS.FF'

Timestamp format in File format used in snowflake is
YYYY-MM-DD"T"HH24:MI:SS.FF

I am assuming that we need to change the code in snowflake connector, please suggest.

**Comment by koszti** [comment]
there is no method to define custom time formats. CSV files should be generated automatically by this target-snowflake that is compatible with every tap with valid singer messages and with the snowflake FILE FORMAT object that you have to create in advance:
```
CREATE file format IF NOT EXISTS {schema}.{file_format_name} type = 'CSV' escape='\\' field_optionally_enclosed_by='"';
```

How did you create the CSV file in your example? It's using `|` as the field delimiter which doesn't look like the default `,` (comma) that this target-snowflake should generate

**Comment by SaurabhJain2611** [comment]
Thanks Peter for your response. I have reverted everything and now after redeploying fresh the automatically generated csv entries for the mysql data are
MYSQL Data
Sample:
Data in mysql
'1000', 'Voyatouch', '0', '2017-03-26 00:57:23', '2017-03-26 00:57:23', '112'

csv entry
"2019-10-23T20:32:21.017141",,"2019-10-23T15:00:15.657624Z",1000,"Voyatouch","2017-03-26T00:57:23+00:00","2017-03-26T00:57:23+00:00",false,112

Here I notice 3 diff  timestamp formats in the csv
 "2019-10-23T20:32:21.017141" (_sdc_batched_at)
"2019-10-23T15:00:15.657624Z" (_sdc_extracted_at)
and 
"2017-03-26T00:57:23+00:00" (table columns)

I have ran this command so the custom format has been removed from snowflake file format
CREATE file format IF NOT EXISTS {schema}.{file_format_name} type = 'CSV' escape='\\' field_optionally_enclosed_by='"'

getting same error
snowflake.connector.errors.ProgrammingError: 100096 (22007): Can't parse '"2017-03-26T00:57:23+00:00"' as timestamp with format 'AUTO'

Please suggest.

**Comment by baderkha** [comment]
@SaurabhJain2611 did you figure out the issue as i'm running t into it today

**Comment by SaurabhJain2611** [comment]
@baderkha 
the file format used for ingesting the data had to be updated with field_optionally_enclosed_by='"'

CREATE FILE FORMAT {database}.{schema}.{file_format_name}
TYPE = 'CSV' ESCAPE='\\' FIELD_OPTIONALLY_ENCLOSED_BY='"';

https://transferwise.github.io/pipelinewise/connectors/targets/snowflake.html#target-snowflake

**Comment by baderkha** [comment]
@SaurabhJain2611  yeah i figured it out too it was the enclosed by i'm pretty sure i had enclosed by " but for some reason it didn't show up so i had to do it through the gui for snowflake . Thanks again though . i think we can close this issue
