### ISSUE TITLE
Errors on running a new environment targeting an empty snowflake instance

### ISSUE THREAD

**Issue by aaronsteers** [transferwise/pipelinewise-target-snowflake#75]
UPDATE: 

Scroll down to [comment #4](https://github.com/transferwise/pipelinewise-target-snowflake/issues/75#issuecomment-631179309) for the findings from the onboarding errors and initial testing/debugging.

---------------------------------------------------
I specified `dbname` but I'm still getting the below errors. The docs don't mention that schema needs to be fully qualified (with the `mydb.` prefix) but perhaps that's the issue?

* `Schema 'RAW' does not exist. Creating... CREATE SCHEMA IF NOT EXISTS RAW`
* `Cannot perform CREATE SCHEMA. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.`

```
INFO Syncing Salesforce data for stream Account
"INFO Making POST request to https://slalom.my.salesforce.com/services/async/41.0/job with body {""operation"": ""queryAll"", ""object"": ""Account"", ""contentType"": ""CSV""}
...
time=2020-05-19 18:42:52 name=target_snowflake level=INFO message=Schema 'RAW' does not exist. Creating... CREATE SCHEMA IF NOT EXISTS RAW
"INFO Making POST request to https://slalom.my.salesforce.com/services/async/41.0/job/7501R00000kVtfUQAS with body {""state"": ""Closed""}
Traceback (most recent call last):
"  File ""/venv/target-snowflake/target-snowflake"", line 10, in <module>
    sys.exit(main())
"  File ""/venv/target-snowflake/lib/python3.7/site-packages/target_snowflake/__init__.py"", line 446, in main
"    persist_lines(config, singer_messages, table_cache)
"  File ""/venv/target-snowflake/lib/python3.7/site-packages/target_snowflake/__init__.py"", line 282, in persist_lines
    stream_to_sync[stream].create_schema_if_not_exists()
"  File ""/venv/target-snowflake/lib/python3.7/site-packages/target_snowflake/db_sync.py"", line 559, in create_schema_if_not_exists
    self.query(query)
"  File ""/venv/target-snowflake/lib/python3.7/site-packages/target_snowflake/db_sync.py"", line 323, in query
"    cur.execute(q, params)
"  File ""/venv/target-snowflake/lib/python3.7/site-packages/snowflake/connector/cursor.py"", line 580, in execute
    errvalue)
"  File ""/venv/target-snowflake/lib/python3.7/site-packages/snowflake/connector/errors.py"", line 97, in errorhandler_wrapper
"    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
"  File ""/venv/target-snowflake/lib/python3.7/site-packages/snowflake/connector/errors.py"", line 73, in default_errorhandler
    done_format_msg=errorvalue.get(u'done_format_msg'))
"snowflake.connector.errors.ProgrammingError: 090105 (22000): Cannot perform CREATE SCHEMA. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.
CRITICAL Error syncing Account: [Errno 32] Broken pipe
Traceback (most recent call last):
"  File ""/venv/tap-salesforce/lib/python3.7/site-packages/tap_salesforce/sync.py"", line 95, in sync_stream
"    sync_records(sf, catalog_entry, state, counter, state_msg_threshold)
"  File ""/venv/tap-salesforce/lib/python3.7/site-packages/tap_salesforce/sync.py"", line 131, in sync_records
    time_extracted=start_time))
"  File ""/venv/tap-salesforce/lib/python3.7/site-packages/singer/messages.py"", line 217, in write_message
"    sys.stdout.write(format_message(message) + '
BrokenPipeError: [Errno 32] Broken pipe
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
"  File ""/venv/tap-salesforce/tap-salesforce"", line 11, in <module>
"    load_entry_point('tap-salesforce==1.4.24', 'console_scripts', 'tap-salesforce')()
"  File ""/venv/tap-salesforce/lib/python3.7/site-packages/tap_salesforce/__init__.py"", line 431, in main
    raise e
"  File ""/venv/tap-salesforce/lib/python3.7/site-packages/tap_salesforce/__init__.py"", line 422, in main
    main_impl()
"  File ""/venv/tap-salesforce/lib/python3.7/site-packages/tap_salesforce/__init__.py"", line 405, in main_impl
"    do_sync(sf, catalog, state)
"  File ""/venv/tap-salesforce/lib/python3.7/site-packages/tap_salesforce/__init__.py"", line 375, in do_sync
    loop.run_until_complete(tasks)
"  File ""/usr/local/lib/python3.7/asyncio/base_events.py"", line 579, in run_until_complete
    return future.result()
"  File ""/venv/tap-salesforce/lib/python3.7/site-packages/tap_salesforce/__init__.py"", line 356, in sync_catalog_entry
"    await loop.run_in_executor(None, sync_stream, sf, catalog_entry, state, state_msg_threshold)
"  File ""/usr/local/lib/python3.7/concurrent/futures/thread.py"", line 57, in run
"    result = self.fn(*self.args, **self.kwargs)
"  File ""/venv/tap-salesforce/lib/python3.7/site-packages/tap_salesforce/sync.py"", line 103, in sync_stream
"    stream, ex)) from ex
Exception: Error syncing Account: [Errno 32] Broken pipe
```

**Comment by aaronsteers** [comment]
I tested now including a two-part name for schema and it seems to get me closer. Now I'm getting a new error which I don't understand:

```
File "/venv/target-snowflake/lib/python3.7/site-packages/target_snowflake/db_sync.py", line 623, in get_table_columns
...
snowflake.connector.errors.ProgrammingError: 001059 (22023): SQL compilation error:
Must specify the full search path starting from database for RAW
--
 


```

**Comment by aaronsteers** [comment]
After reverting back to the not-fully-qualified `default_target_schema_name`, and after ensuring that the user's default database in snowflake matches the destination database, I'm getting a new error message but still stuck in `create_schema_if_not_exists()` - 

```
File "/venv/target-snowflake/target-snowflake", line 10, in <module>
    sys.exit(main())
File "/venv/target-snowflake/lib/python3.7/site-packages/target_snowflake/__init__.py", line 446, in main
    persist_lines(config, singer_messages, table_cache)
File "/venv/target-snowflake/lib/python3.7/site-packages/target_snowflake/__init__.py", line 282, in persist_lines
    stream_to_sync[stream].create_schema_if_not_exists()
File "/venv/target-snowflake/lib/python3.7/site-packages/target_snowflake/db_sync.py", line 551, in create_schema_if_not_exists
    schema_rows = list(filter(lambda x: x['SCHEMA_NAME'] == schema_name.upper(), self.table_cache))
File "/venv/target-snowflake/lib/python3.7/site- 
packages/target_snowflake/db_sync.py", line 551, in <lambda>
    schema_rows = list(filter(lambda x: x['SCHEMA_NAME'] == schema_name.upper(), self.table_cache))
KeyError: 'SCHEMA_NAME'
```

Any ideas?

**Comment by aaronsteers** [comment]
Found the reference where the KeyError is occurring. Looks like a bug of some sort with pre-cached schema objects? Perhaps related to having an empty database?

https://github.com/transferwise/pipelinewise-target-snowflake/blob/master/target_snowflake/db_sync.py#L551

```
    def create_schema_if_not_exists(self):
        schema_name = self.schema_name
        schema_rows = 0

        # table_cache is an optional pre-collected list of available objects in snowflake
        if self.table_cache:
            schema_rows = list(filter(lambda x: x['SCHEMA_NAME'] == schema_name.upper(), self.table_cache))
        # Query realtime if not pre-collected
        else:
            schema_rows = self.query(f"SHOW SCHEMAS LIKE '{schema_name.upper()}'")

        if len(schema_rows) == 0:
            query = "CREATE SCHEMA IF NOT EXISTS {}".format(schema_name)
            self.logger.info("Schema '{}' does not exist. Creating... {}".format(schema_name, query))
            self.query(query)

            self.grant_privilege(schema_name, self.grantees, self.grant_usage_on_schema)

```

**Comment by aaronsteers** [comment]
Creating a dummy table in the empty schema appears to have fixed the above error message.

A few findings to summarize the above threads:

1. Can we clarify in the docs that the schema_name should not include the database name as a prefix?
2. Can we confirm if the user must have their default database set to the target database for this target to work correctly? If so, any way to send a quick "USE DATABASE {dbname}" since the dbname is already provided in the config?
3. Can someone else confirm my hypothesis if the above KeyError is indeed a bug related to targeting an empty schema and database?

Happy to help contribute code if I can.

**Comment by aaronsteers** [comment]
Posting a recap here:

1. Confirmed: The `schema_name` should not include database name as a prefix.
2. Still to be confirmed where user needs to have the target database as their default DB.
3. 🐛 **Confirmed BUG:** On empty schemas, a `KeyError ('SCHEMA')` is triggered due to a null record being passed around in place of an actual table. The only workaround I've identified is to create a dummy table - e.g. `CREATE TABLE dummy_DELETEME AS SELECT 1 AS ColA`

**Comment by koszti** [comment]
hey @aaronsteers thanks for the details. Regarding point 3), the same bug also reported in https://github.com/transferwise/pipelinewise-target-snowflake/issues/78 and it's been fixed by https://github.com/transferwise/pipelinewise-target-snowflake/pull/81 and will be merged and released to pypi soon.

Regarding point 1) and 2) please give me some time, I need to check the expected behaviour and I'll try to give detailed answers.

**Comment by aaronsteers** [comment]
Thanks very much @koszti! No worries about the #1 (resolved) but it would be good to confirm #2, being the issue about the default DB needing to match the target DB.

**Comment by koszti** [comment]
Just to confirm you're right in point 1. The `schema_name` should not include database name as a prefix. Updated the doc [here](https://github.com/transferwise/pipelinewise-target-snowflake/commit/56a92f5cfa05de7c9fad826054058092e5f17ca5#diff-04c6e90faac2675aa89e2176d2eec7d8R145) .

Regarding point 2) I think it's a permission problem and I could reproduce the same problem only if the user didn't have the all the required permissions on the database. You're right and the documentation didn't clarify the required roles and permissions. I updated the documentation now [here](https://github.com/transferwise/pipelinewise-target-snowflake#pre-requirements) and [here](https://transferwise.github.io/pipelinewise/connectors/targets/snowflake.html). Can you please try and let me know if that solves your problem?

Running `USE DATABASE {dbname}` as an extra command after connecting to snowflake is ideally not required and may cause some other issues. The database name explicitly defined when we create the snowflake connection: https://github.com/transferwise/pipelinewise-target-snowflake/blob/09ecd645f135e4d90c453f9774cb21f3a018093c/target_snowflake/db_sync.py#L299 . 

I hope this helps.

**Comment by aaronsteers** [comment]
@koszti - I realized I'd left this open - but I believe all the above is now resolved. Thanks, as always, for your support!
