### ISSUE TITLE
Option to not delete from S3 after load?

### ISSUE THREAD

**Issue by aaronsteers** [transferwise/pipelinewise-target-snowflake#76]
Hello. It looks like the all files are being deleted from S3 after being loaded. Is there any way currently to retain those files in S3 for data lake / archival purposes? 

And, if not possible today, would you accept a PR with this feature?

Thanks very much!

**Comment by koszti** [comment]
hello, you're right, successfully loaded files are being deleted from s3 automatically and currently there is no option to keep the files. Maybe you can consider to add an optional `delete_files_on_s3` parameter into `config.json` that defaults to `True`. 

PRs are welcome, and if you include unit tests, and not changing the default behaviour then we can usually review and accept quicker.

Just please make sure to keep the current behaviour as default, so if `delete_files_on_s3` is not in `config.json` then files need to be deleted.

**Comment by aaronsteers** [comment]
@koszti - Thanks very much for your reply. I understand and appreciate the need to retain the current default. What about a setting name like `retain_files_in_s3` option, which defaults to `false`? It might not be much difference, but I feel like saying "yes" to deleting files just sounds riskier than declining to "retain" the saved files.

Either way, the functionality is basically the same and we're agreed on the default. The other thing that comes to mind is then a desire to let the user override the naming scheme. So I'd like to also add an (optional) setting for `s3_filename_pattern` or `s3_naming_scheme` (or similar) which would be combined with the existing `s3_prefix` and would allow the user to further customize the target file names if needed.

**Comment by aaronsteers** [comment]
Post PR here: #77

**Comment by koszti** [comment]
Similar feature added by #178 , #180 and #189 and released as part of 1.13.0

New options:

`archive_load_files`: (Default: False) When enabled, the files loaded to Snowflake will also be stored in archive_load_files_s3_bucket under the key `/{archive_load_files_s3_prefix}/{schema_name}/{table_name}/`. All archived files will have tap, schema, table and archived-by as S3 metadata keys. When incremental replication is used, the archived files will also have the following S3 metadata keys: `incremental-key`, `incremental-key-min` and `incremental-key-max`.

`archive_load_files_s3_prefix`: (Default: "archive") When archive_load_files is enabled, the archived files will be placed in the archive S3 bucket under this prefix.

`archive_load_files_s3_bucket`: (Default: Value of s3_bucket) When archive_load_files is enabled, the archived files will be placed in this bucket.
