### ISSUE TITLE
Ability to override default snowflake role

### ISSUE THREAD

**Issue by aaronsteers** [transferwise/pipelinewise-target-snowflake#96]
It looks like there's not currently a way to override the default role for the snowflake user. Is this correct, and if so, is it something we could be okay to add?

**Comment by Samira-El** [comment]
Hey, indeed, target snowflake uses the default role of the provided user.

I think having ability to override it by providing an optional `role` in the config would be a nice little feature to have.

**Comment by Samira-El** [comment]
Overriding the role has been possible thanks to Peter's PR.
Closing this.
